Description: EC2 instance with SSM and Docker

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM

  Profile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: /
      Roles: [!Ref Role]

  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow TCP traffic on ports 80, 8080, 8085, 54663
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 8085
          ToPort: 8085
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 8111
          ToPort: 8111
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 54663
          ToPort: 54663

  Server:
    Type: AWS::EC2::Instance

    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M

    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          application_installation:
            - install_cfn
            - install_apps
        install_cfn:
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Join 
                - ''
                - - |
                    [main]
                  - stack=
                  - !Ref 'AWS::StackId'
                  - |+

                  - region=
                  - !Ref 'AWS::Region'
                  - |+

              mode: '000400'
              owner: root
              group: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Join 
                - ''
                - - |
                    [cfn-auto-reloader-hook]
                  - |
                    triggers=post.update
                  - |
                    path=Resources.Server.Metadata.AWS::CloudFormation::Init
                  - 'action=/opt/aws/bin/cfn-init -v '
                  - '         --stack '
                  - !Ref 'AWS::StackName'
                  - '         --resource Server '
                  - '         --configsets application_installation '
                  - '         --region '
                  - !Ref 'AWS::Region'
                  - |+

              mode: '000400'
              owner: root
              group: root
          services:
            sysvinit:
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
        install_apps:
          packages:
            yum:
              docker: []
          files:
            /etc/index.html:
              content: !Sub |
                <!DOCTYPE html>
                <html>
                <head>
                  <title>Welcome to ${AWS::StackName}</title>
                  <style>
                    body {
                      font-family: Arial, sans-serif;
                      background-color: #f5f5f5;
                      margin: 0;
                      padding: 0;
                      display: flex;
                      flex-direction: column;
                      align-items: center;
                      justify-content: center;
                      height: 100vh;
                    }
                    h1 {
                      color: #007bff;
                      font-size: 36px;
                      margin-bottom: 20px;
                    }
                    p {
                      color: #333;
                      font-size: 18px;
                      line-height: 1.5;
                      max-width: 600px;
                      text-align: center;
                      margin-bottom: 20px;
                    }
                    a {
                      color: #007bff;
                      text-decoration: none;
                    }
                    a:hover {
                      text-decoration: underline;
                    }
                    b {
                      font-weight: bold;
                    }
                  </style>
                </head>
                <body>
                  <h1>Welcome to ${AWS::StackName}!</h1>
                  <p>This server is running an evaluation environment for <a href="https://www.atlassian.com/software/bamboo" target="_blank">Atlassian Bamboo</a></p>
                  <p><b>The configuration in use is meant for education and research purposes only and is not intended for production use.</b></p>
                  <p>Get started by opening a link to this host on port <b>8085</b>.  Then proceed by completing the installation.</p>
                  <p>http://hostname:8085</p>
                  <h2>Have fun evaluating Bamboo!</h2>
                </body>
                </html>
              mode: "000444"
              owner: root
              group: root
          services:
            sysvinit:
              docker:
                enabled: 'true'
                ensureRunning: 'true'

    Properties:
      InstanceType: t3.large
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-ebs}}"
      IamInstanceProfile: !Ref Profile
      SecurityGroups:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}

      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            exec > >(tee /var/log/user-data.log) 2>&1
            set
            yum update -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Server --configsets application_installation
            docker run --detach --publish 80:80 --volume /etc/index.html:/usr/share/nginx/html/index.html:ro nginx
            docker volume create jenkins_home
            docker run --detach --publish 8080:8080 --publish 50000:50000 --volume jenkins_home:/var/jenkins_home  --name jenkins jenkins/jenkins:lts
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Server
 
Outputs:
  URL:
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - Server
          - PublicDnsName
        - :8085/
    Description: Application URL