version: '3'

services:
  jenkins:
    mem_reservation: "500M"
    mem_limit: "1G"
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
    driver: local

